In [2]:
import numpy as np

In [9]:
array = np.array([0,2,4,6,8])
print(array)

[0 2 4 6 8]


In [18]:
# Chiều của mảng
print('dimension:', array.ndim)

# Kích thước bytes của mảng
print('bytes:',array.itemsize)

# Kích thước dòng cột
print('shape:', array.shape)

# Kiểu dữ liệu
print('type:', array.dtype)

# Tổng phần tử trong mảng
print('Number of elements:', array.size)

dimension: 1
bytes: 8
shape: (5,)
type: int64
Number of elements: 5


In [14]:
# Khởi tạo mạng với giá trị cho trước
# np.array([mảng 1 chiều, ...])
array2 = np.array(
    [
        [1,2,3,4,5,6,7,8],
        [9,10,11,12,13,14,15,16]
    ]
)

print(array2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [24]:
# Truy giá trị phần tử bằng chỉ số
print('Index at row 0 column 2:', array2[0,2])
print('Index at row 1 column 4:', array2[1,4])

# Lấy dòng
print(array2[0, :])

# Lấy cột
print(array2[:, 3])

# Lấy hết bỏ 2 cột cuối
print(array2[:, :-2])

# Chỉ lấy 2 cột cuối
print(array2[:, -2:])

# Sửa giá trị
array2[1,4] = 999
print(array2)

# Sửa giá trị ở tất cả dòng theo cột
array2[:, 3] = 777
print(array2)


Index at row 0 column 2: 3
Index at row 1 column 4: 99
[1 2 3 4 5 6 7 8]
[ 4 12]
[[ 1  2  3  4  5  6]
 [ 9 10 11 12 99 14]]
[[ 7  8]
 [15 16]]
[[  1   2   3   4   5   6   7   8]
 [  9  10  11  12 999  14  15  16]]
[[  1   2   3 777   5   6   7   8]
 [  9  10  11 777 999  14  15  16]]


In [30]:
# Khởi tạo mảng với giá trị 0 theo shapearr
# np.zeros(shape)
zeros = np.zeros((4,4))
print(zeros)

# np.ones(shape)
ones = np.ones((3,3))
print(ones)

# np.full(shape, value)
full = np.full((5,5), 22)
print(full)

# Khởi tạo mảng random
randoms = np.random.rand(4,2)
print(randoms)

# Khởi tạo mạng random số nguyên
randoms_int = np.random.randint(1, 9, size=(3,3))
print(randoms_int)

# Khởi tạo ma trận identity
identity = np.identity(3)
print(identity)

# Lặp lại kết quả theo số lần
# axis = 0 lặp kết quả dạng cột
# axis = 1 lặp kết quả dạng hàng
arr = np.array([[1,2,3]])
result = np.repeat(arr,3, axis=0)
result2 = np.repeat(arr,3, axis=1)
print(result)
print(result2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[22 22 22 22 22]
 [22 22 22 22 22]
 [22 22 22 22 22]
 [22 22 22 22 22]
 [22 22 22 22 22]]
[[0.42062488 0.34401577]
 [0.31165647 0.3883334 ]
 [0.57607734 0.58938629]
 [0.67296372 0.67472686]]
[[7 5 3]
 [8 1 7]
 [6 6 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [31]:
# # Sử dụng hàm copy để tránh việc bị đè giá trị gốc
# VD: gán arr2 = arr
# Khi thay đổi giá trị trong arr2 thì arr sẽ bị thay đổi theo
arr2 = arr.copy()
print(arr2)

[[1 2 3]]


In [36]:
# Các phép toán cơ bản
# Numpy hỗ trợ các phép toán vào các phần tử trong mảng hoặc thực hiện các toán tử với các mảng khác
# Tham khảo thêm

arr = np.array([1,2,3,4])
print(arr + 2)
print(arr - 1)
print(arr * 2)
print(arr / 2)
print(arr ** 2)
print(arr + arr)

# Tính sin
print(np.sin(arr))
# Tín cos
print(np.cos(arr))
# Tổng giá trị các phần tử
print(np.sum(arr))
# Tích giá trị các phần tử
print(np.prod(arr))

[3 4 5 6]
[0 1 2 3]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[2 4 6 8]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
10
24


In [37]:
# Min & max
arr = [0,2,4,6,8]
print(np.min(arr))
print(np.max(arr))

0
8
